apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: test
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - name: http
      nodePort: 30000
      port: 9898
      targetPort: 9898
      protocol: TCP
      targetPort: http
    - port: 9999
      targetPort: grpc
      protocol: TCP
      name: grpc
